#!/bin/bash
#
# kmodtool-kmodgenca -  Helper script to create CA / Keypair for sign modules
# Copyright (c) 2017 Stanislas Leduc <stanislas.leduc@balinor.net>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

cacert_config="/etc/kmodtool/cacert.config"
keyname="$(hostname)"-"$(od -vAn -N4 -tu4 < /dev/urandom | awk '{print $1}')"

echo "Update cacert_config..."
sed -i "s#\(O = \).*#\1$(hostname)#" $cacert_config
sed -i "s#\(CN = \).*#\1$keyname#" $cacert_config
sed -i "s#\(emailAddress = \).*#\1kmodtool@$(hostname)#" $cacert_config

echo "Generate new keypair..."
newgrp akmods << genkey
umask 037
openssl req -x509 -new -nodes -utf8 -sha256 -days 3650 -batch \
 -config $cacert_config -outform DER \
 -out /etc/kmodtool/keys/$keyname.der \
 -keyout /etc/kmodtool/keys/$keyname.priv
genkey

# Ensure that akmods group can read keys
chmod g+r /etc/kmodtool/keys/$keyname.*

# Update symlink for use current keypair
ln -sf /etc/kmodtool/keys/$keyname.der /etc/kmodtool/keys/public_key.der
ln -sf /etc/kmodtool/keys/$keyname.priv /etc/kmodtool/keys/private_key.priv

exit 0
